name: Debug Example

on: push

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
    - name: Debug secret
      run: echo "::debug::Secret value is $TEST_SECRET"
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}

